In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('marketing_campaigns.csv')
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,5,0,0,0,0,0,0,3,11,0

<b>Defining Hypothesis<b>
<br>
    
Null Hypothesis (H0): There is no significant difference in response rates between customers with a Bachelor's degree and customers with a PHD degree.
<br>

Alternative Hypothesis (HA): There is a significant difference in response rates between customers with a Bachelor's degree and customers with a PHD degree.

In [3]:
df['Education'].unique()

array(['Graduation', 'PhD', 'Master', 'Basic', '2n Cycle'], dtype=object)

In [5]:
# Filter relevant columns
df_ab_test = df[['Education', 'Response']]

# Create groups
group_bachelor = df_ab_test[df_ab_test['Education'] == 'Graduation']
group_phd = df_ab_test[df_ab_test['Education'] == 'PhD']

In [7]:
#Calculating conversion rate for each group
conversion_rate_bachelor = group_bachelor['Response'].mean()
conversion_rate_master = group_phd['Response'].mean()

print("Conversion Rate for Bachelor's degree group:", conversion_rate_bachelor)
print("Conversion Rate for PHD degree group:", conversion_rate_master)

Conversion Rate for Bachelor's degree group: 0.13487133984028393
Conversion Rate for PHD degree group: 0.20781893004115226

In [8]:
#Perform Statistical Analysis
import scipy.stats as stats

# Perform two-sample t-test
t_stat, p_value = stats.ttest_ind(group_bachelor['Response'], group_phd['Response'], equal_var=False)

print("t-statistic:", t_stat)
print("p-value:", p_value)

t-statistic: -3.4655780617383893
p-value: 0.0005574775798950022

Interpret the Results

If the p-value is below a predetermined significance level (e.g., 0.05), we reject the null hypothesis and conclude that there is a significant difference in response rates between customers with a Bachelor's degree and customers with a Master's degree.
If the p-value is above the significance level, we fail to reject the null hypothesis and conclude that there is not enough evidence to suggest a significant difference.
<br>
Step 6: Make Informed Decisions

Based on the results, you can make decisions regarding campaign strategies targeting customers with different educational backgrounds. If the difference in response rates is significant, you may consider adjusting marketing approaches or tailoring campaigns to specific customer segments.
Note: The A/B testing process described here is a simplified example using only one feature (Education). In practice, you can explore more complex hypotheses and include additional factors for a comprehensive analysis. Additionally, it's crucial to ensure an adequate sample size and consider other factors such as demographics, campaign characteristics, and customer behavior when interpreting the results and making decisions.



In addition to Education, you can perform A/B testing on other variables in the dataframe to analyze the impact on response rates or other relevant metrics. Here are a few examples:

Marital_Status: Compare response rates between different marital status categories, such as Married, Single, Divorced, etc.

Income: Analyze the effect of income levels on response rates by dividing customers into different income groups.

Kidhome and Teenhome: Investigate the influence of the number of children or teenagers at home on response rates.

AcceptedCmp1, AcceptedCmp2, AcceptedCmp3, AcceptedCmp4, AcceptedCmp5: Evaluate the effectiveness of different marketing campaigns by comparing the response rates between customers who accepted each campaign and those who didn't.

NumWebPurchases, NumCatalogPurchases, NumStorePurchases: Assess the impact of purchasing behavior on response rates by comparing customers' response rates based on their number of purchases through different channels.

Remember, the variables you choose for A/B testing should be relevant to your business goals and hypotheses. It's important to analyze and understand the relationship between the variable being tested and the desired outcome to make meaningful and actionable conclusions.



t-statistic: -3.4655780617383893
p-value: 0.0005574775798950022

In statistical hypothesis testing, the t-statistic and p-value are important measures used to assess the significance of the results obtained.

The t-statistic measures the difference between the sample means of two groups (in A/B testing, typically the control group and the experimental group), relative to the variability within each group. It indicates the magnitude of the difference between the groups and how likely that difference is due to random chance. In your case, the t-statistic value is -3.4655780617383893.

The p-value is the probability of observing a t-statistic as extreme as the one calculated, assuming that the null hypothesis is true. In A/B testing, the null hypothesis usually states that there is no significant difference between the groups being compared. A small p-value indicates strong evidence against the null hypothesis, suggesting that the observed difference between the groups is unlikely to be due to random chance alone. In your case, the p-value is 0.0005574775798950022.

Interpreting the results:
Based on the given t-statistic and p-value:

The t-statistic of -3.4655780617383893 indicates a substantial difference between the groups being compared.
The p-value of 0.0005574775798950022 is less than the commonly used significance level of 0.05. This means that there is strong evidence to reject the null hypothesis and conclude that the observed difference between the groups is statistically significant.
In simpler terms, the results suggest that the difference observed in the response rates between the groups is likely not due to random chance, but rather indicates a meaningful difference between the groups. This provides evidence to support the conclusion that the variable being tested (in this case, the one used for A/B testing) has a significant impact on the response rates.

It's important to note that further analysis and interpretation of the specific context and goals of your A/B testing are necessary to draw more concrete conclusions and make informed decisions based on these results.




The t-statistic is a measure that tells us how different two groups are from each other. In this case, we are comparing two groups based on a specific variable. The t-statistic value of -3.4655780617383893 suggests that there is a noticeable difference between these two groups.

The p-value is a number that helps us determine if the observed difference is meaningful or just due to chance. In our case, the p-value is 0.0005574775798950022. Think of the p-value as a measure of confidence. A smaller p-value indicates stronger evidence that the observed difference is not due to random chance alone.

In simple terms, the results suggest that there is a significant difference between the two groups based on the variable we are comparing. This difference is unlikely to happen by chance alone. So, we can conclude that the variable we are testing has a real impact on the results we are observing.

It's important to consider the specific context and purpose of the test to fully understand the implications of these results. A/B testing helps us make informed decisions by comparing different groups and determining which factors influence the outcomes we are interested in.